matrix:
    include:
        - os: osx
          osx_image: xcode9.4
          language: node_js
          node_js: "10"
        - os: osx
          osx_image: xcode9.4
          language: node_js
          tranode_js: "10"

env:
    matrix:
        - ELECTRON_CACHE=$HOME/.cache/electron ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder TARGET_OS="osx"
        - ELECTRON_CACHE=$HOME/.cache/electron ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder TARGET_OS="osx"
        - ELECTRON_CACHE=$HOME/.cache/electron ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder TARGET_OS="osx"

cache:
    yarn: true
    directories:
        - node_modules
        - "$HOME/.cache/electron"
        - "$HOME/.cache/electron-builder"

script: bash buildRelease.sh

before_cache:
    - rm -rf $HOME/.cache/electron-builder/wine

deploy:
    provider: releases
    api_key:
        secure: ZIquTH9wBMZDh6YgF/A2oe3VOxFmYXK0lW+uR09i5hVFdmlV+ghP7xmQuxpZ0SAlXoKmzSQURP1qhxYgWsf33c7dV3YzlWrGedrAQv5W/arG9nt2IWAo/qqeIV+gsxmJXc5dud1kBXtt+PZsW4cJkJvXkjhEDe1DvO9Al8/N+ODryYDUMNC3MQS72H1Heu4+T/t9E9tTTmX4I9RS12DPBpXnta1ZfRKwB67C1+W5fClDFgs65PTV5Ja38IVEGsu6E0kIgpzPzoLF9PAgf+YsglCK0hObXSw3Jiiq1iveG2/maJ5t9XkUgFlQQqa/sfQ4DGpeEqZkSaPW3p4yL0rguRgefEgKgsX+CNo5VO9aZkTlS21HOXnwpklFQQJO/TOxQdu1sHQwU5eFGfcfWC9zlvE+pSzAfcmCW9w5gnuWBXnarSJ2l53uwSak++6rXChQ7cUY29GidJ/fIPy4l/IhRso6WcL6AEbNHD5WocF+ttOkyMtZuXx3v8ZaQfPZ3ZS+JFm0YeArkpJ40mZne4laesRb+wWsNA420NeCxP+a4Tupxs29vt1PllYPZ183Hq0/VmopfcZt2+XJCeyyPSXcVEw2iAFQ92gBvkU6B7llNR0Eh6KtofQCMP+R1RG5HZPEZR7rC1nPG3c1t6kcH5pae/wEjlc50U3ksnh9BIetxzY=
    file_glob: true
    file: 
        -'/dist/Branch-*.dmg'
        -'/dist/Branch*.exe'
        -'/dist/branch_*.deb'
    skip_cleanup: true
    on:
        tags: true
        repo: D0miH/branch
